### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mulshine** [spiricom/CAudioLibrary#1]
1. Implement more AudioUnits:
- [ ] (Dan)-limited oscillators 
- [ ] Compressor
- [ ] FIR Filter 
- [ ] Various STK filters (maybe also from Filter C++ book)
- [ ] Fun reverbs
- [ ] Impulse
- [ ] ADSR
- [ ] Sequencer 
- [ ] Physical modeling of Strings: Karplus-Strong / Extended Karplus-Strong
- [ ] Physical modeling of Winds: Banded Waveguide / Blowhole / Blowtar
- [ ] (Maybe) Physical modeling of Drums/Membranes
- [ ] Some quirky stuff (neuron synth, Nick Collins chaos/errant sound)
- [ ] Add our higher level Instruments (808, etc)

2. Meet our Embedded library standards
- [ ] Implement Accurate and Efficient versions of everything
- [ ] Different wavetable lengths / resolutions
- [ ] Codify wavetable generation tools 

3. Paper preparation 
- [ ] Find examples of Audio Library presentations/papers
- [ ] Read more about Object-Oriented Programming in C
- [ ] Read about reasons for migrating to embedded C++ (Dan Saks)
- [ ] Keep a list of pros/cons of our Library (specifically the idea of OOPC) (i.e. Con: inlining functions eliminates the compilers ability to determine whether you've mismatched L- and R-value types, thus producing run-time instead of build-time errors, making debugging more difficult) 
 
4. Early Applications
- [ ] Feedback trombone
- [ ] Electrosteel

5. Future Library Features:
- [ ] STK/JUCE-like Debug support
- [ ] File In/Out/Read/Write/Playback
